# Welcome to Jekyll!

# Website settings
title: "Ivan"
description: "Ivan Kresic github"
keywords: "Ivan,Kresic,blog,github,gh-pages"
theme: jalpc
baseurl: "/"
url: "https://github.com/IvanKresic/IvanKresic.github.io"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Ivan'
  first_name: 'Ivan'
  last_name: 'Kresic'
  email: 'ivan.kresic9091@gmail.com'
  github_username: 'IvanKresic'
  head_img: 'static/img/landing/Jack.jpg'
  desc: 'I am a Software Engineer with web, mobile and IoT development expirience. Besides engineering I have a great interest in business managenent and development processes.Life is a continuous learning process, so learning at least one thing per day is must, and traveling makes that learning expirience more noble. What is the point of learning new things, if you are not going tomeet new people with who you are going to exchange your knowledge?'

# sections
sections:
  - id: 'about-me'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'career'
    i18n: 'nav.career'
    name: 'Career'
    tpl: 'career.html'
    css: 'timeline'

  - id: 'skills'
    i18n: 'nav.skills'
    name: 'Skills'
    tpl: 'skills.html'
    css: 'team'

  - id: 'projects'
    i18n: 'nav.projects'
    name: 'Projects'
    tpl: 'projects.html'
    css: 'project'

  - id: 'blog'
    i18n: 'nav.blog'
    name: 'Blog'
    tpl: 'blog.html'
    css: 'testimonials navy-section'

  - id: 'links'
    i18n: 'nav.link'
    name: 'Links'
    tpl: 'links.html'
    css: 'contact'

# localization
languages:
  - locale: 'en'
    flag: 'static/img/flags/United-States.png'
  - locale: 'zh'
    flag: 'static/img/flags/China.png'

# blog img path
img_path: 'http://www.jack003.com/static/img/blog'

# donate
donate:
  wechat: 'static/img/pay/w1.jpeg'
  # alipay: 'static/img/pay/alipay.png'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: jalpc
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-73784599-1

# growingIO
gio:
  id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
